ALTER TABLE account ADD COLUMN user_id UUID REFERENCES users(id);
ALTER TABLE account ADD COLUMN currency VARCHAR(10) NOT NULL DEFAULT 'INR';
ALTER TABLE account ALTER COLUMN balance TYPE DECIMAL(19, 2);
ALTER TABLE transaction ALTER COLUMN amount TYPE DECIMAL(19, 2);
ALTER TABLE entry ALTER COLUMN amount TYPE DECIMAL(19, 2);
